Implementation service statement api using lumen
savantcare/emr pull request #146
Opened 2020-10-12 11:01 UTC by akash-grmtech

2020-10-12 11:21 UTC, rajgrmtech commented on servers/lumen/app/Http/Controllers/ServiceStatementController.php
>          return response()->json(ServiceStatement::find($pServerSideRowUuid));
Line no: 18. variable name should be '$serviceStatementQueryResultObj' instead of '$ServiceStatementQuery'

2020-10-12 11:26 UTC, rajgrmtech commented on webclient/components/1time-Mrow-1Field/service-statement/db/client-side/initialize-on-first-load.vue
> +    const proRemsFromDB = await clientSideTable.api().get(clientSideTable.apiUrl)
Line no: 27. Why 'Rems' word used in service statement component?

2020-10-13 05:02 UTC, rajgrmtech commented on webclient/components/1time-Mrow-1Field/service-statement/edit-layer/ss-edit-design-1.vue
> +      })
Update client side table if api response failed

2020-10-13 08:18 UTC, rajgrmtech commented on servers/lumen/app/Http/Controllers/ServiceStatementController.php
>          // return response()->json(ServiceStatement::all());
update recordChangedByIpAddress field.
Ref: weightController.php

2020-10-13 12:45 UTC, rajgrmtech approved these changes

2020-10-13 12:45 UTC, rajgrmtech commented on servers/lumen/routes/web.php
> +    $router->put('service-statements/v20/{pServerSideRowUuid}', ['uses' => 'ServiceStatementController@update']);
Remove update routing

2020-10-13 12:45 UTC, rajgrmtech commented on servers/lumen/routes/web.php
> +    $router->options('service-statements/v20/{pServerSideRowUuid}', function () {
Remove option routing for update

2020-10-16 06:24 UTC, vikaskedia requested changes

2020-10-16 06:24 UTC, vikaskedia commented on webclient/components/1time-Mrow-1Field/service-statement/db/client-side/structure/master-table-of-service-statements.js
> +      serviceStatementFieldIdFromServiceStatementMaster: this.uid(() => intUniqueId()), // if this is not set then update based on primary key will not work This is the unique ID for each service sta
SS a is added.
SS a is deleted
SS a is added

There will be a problem.

2020-10-16 06:28 UTC, vikaskedia requested changes

2020-10-16 06:28 UTC, vikaskedia commented on webclient/components/1time-Mrow-1Field/service-statement/db/client-side/initialize-on-first-load.vue
> +import clientSideTable from '~/components/1time-Mrow-1Field/service-statement/db/client-side/structure/patient-table-of-service-statements.js'
more readable would be:

step1-init-search-phrases
step2-init-ss-field-names
step3-get-latest-data-from-db-server

2020-10-16 20:40 UTC, merged