implement authentication from savantcare
savantcare/emr pull request #241
Opened 2020-11-24 14:24 UTC by akash-grmtech

2020-11-25 05:08 UTC, rajgrmtech commented on webclient/pages/pf/index.vue
> +        client_id: 'superstars-discourseonhttp',
Why you use superstars client_id?

2020-11-25 06:57 UTC, vikaskedia requested changes

2020-11-25 06:57 UTC, vikaskedia commented on webclient/pages/pf/index.vue
> +        client_id: 'superstars-discourseonhttp',
you can use the superstar ID.

But next time do not submit code without testing thast it work ?

2020-11-26 08:23 UTC, closed without merging

2020-11-26 08:23 UTC, akash-grmtech commented
Ok Sir