Get correlate to work from button
savantcare/emr pull request #254
Opened 2020-11-30 13:54 UTC by akash-grmtech

2020-11-30 14:01 UTC, akash-grmtech commented
Previous 
<img width="1566" alt="Screenshot 2020-11-30 at 7 29 35 PM" src="https://user-images.githubusercontent.com/58842755/100618915-75137680-3342-11eb-8629-0dfb510e5c19.png">

Fixed
<img width="1557" alt="Screenshot 2020-11-30 at 7 27 37 PM" src="https://user-images.githubusercontent.com/58842755/100619011-91afae80-3342-11eb-996a-34b155d88a33.png">

2020-12-01 04:54 UTC, rajgrmtech requested changes

2020-12-01 04:54 UTC, rajgrmtech commented on webclient/components/papers/correlate/graph-design-1.vue
> +          height: 500, // on page load default height should be 50% of page height, ie; 700px. We have developed this software to run on 1440*900
Above given chart height/width and their documentation not match.
Update documentation.

2020-12-01 04:54 UTC, rajgrmtech commented on webclient/components/papers/correlate/design-2.vue
> +      <graph></graph>
1. Add documentation - Why we change el-dialog width from 100% to 80%?
2. Improve name. It should be 'correlateGraphCt' instead of 'graph'

2020-12-01 06:45 UTC, merged

2020-12-01 06:45 UTC, vikaskedia approved these changes