examination save edit delete data to database
savantcare/emr pull request #337
Opened 2021-02-22 13:39 UTC by akash-grmtech

2021-02-24 08:26 UTC, rajgrmtech commented on webclient/components/patient-data/examination/db/client-side/structure/examination-of-a-patient-table.js
>        psychomotor_multi_select: this.string(null).nullable(),
Remove unused column 'patientUuid'

2021-02-24 08:38 UTC, rajgrmtech requested changes
Number of column in orm, number of column in create function in laravel controller and number of column in table structure given by you in server-side folder, all are different. How is it possible?

2021-02-24 09:32 UTC, akash-grmtech commented on webclient/components/patient-data/examination/db/client-side/structure/examination-of-a-patient-table.js
>        psychomotor_multi_select: this.string(null).nullable(),
DONE

2021-02-26 06:20 UTC, rajgrmtech approved these changes

2021-02-26 08:39 UTC, sanjay-grmtech approved these changes

2021-02-26 08:39 UTC, merged